spring.datasource.url=jdbc:mysql://localhost:3306/sme_db
spring.datasource.username=root
spring.datasource.password=211425Fsql.

spring.jpa.hibernate.ddl-auto=update
sme.jwt.secret=holalucacomoestassoyflor0987654321